data_simulator:
  manifest_filepath: /home/tarushi/tarushi_folder/speaker_diarization/input_manifest.jsonl
  sr: 16000
  random_seed: 42
  num_workers: 1
  session_config:
    num_speakers: 2
    num_sessions: 5
    session_length: 15
  session_params:
    max_audio_read_sec: 10
    sentence_length_params:
    - 1
    - 0.5
    dominance_var: 0.1
    min_dominance: 0.1
    turn_prob: 0.95
    mean_silence: 0.05
    mean_silence_var: 0.01
    per_silence_var: 0.01
    per_silence_min: 0.0
    per_silence_max: -1
    mean_overlap: 0.15
    mean_overlap_var: 0.02
    per_overlap_var: 0.01
    per_overlap_min: 0.0
    per_overlap_max: -1
    start_window: false
    window_type: null
    window_size: 0.0
    start_buffer: 0.0
    split_buffer: 0.0
    release_buffer: 0.0
    normalize: true
    normalization_type: equal
    end_buffer: 1.0
  outputs:
    output_dir: /home/tarushi/tarushi_folder/speaker_diarization/simulated_output
    output_filename: simulated_output
    overwrite_output: true
    output_precision: 2
  background_noise:
    add_bg: false
    background_manifest: null
    num_noise_files: 0
    snr: 20
    snr_min: null
    snr_max: null
  segment_augmentor:
    add_seg_aug: false
  session_augmentor:
    add_sess_aug: false
  speaker_enforcement:
    enforce_num_speakers: false
    enforce_time:
    - 0.0
    - 0.8
